spring:
  application:
    name: cj_alimtalk_service
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    password: cjdb
    username: cjdb
    url: jdbc:log4jdbc:mariadb://172.30.1.112:3306/cjdb
  main:
    web-application-type: none
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # resources 아래 application-secret.yml 로드 (없으면 무시)
  config:
    import: optional:classpath:application-secret.yml